### PR TITLE
Create 2022-12-08_File_Upload_And_Optional_Questions_Processing.md

### PR DESCRIPTION
**Pull request by oliverquinlan**
# PR Checklist

- [x ] If you are proposing a new decision record document, used the right template for that
      - ([ADR](https://github.com/alphagov/forms/blob/main/ADR/ADRXXX-architecture-decision-record-template.md), [decision-record](https://github.com/alphagov/forms/blob/main/decision-record/DRXXX-decision-record-template.md), engagement, [research](https://github.com/alphagov/forms/blob/main/research/YYYY-MM-DD-template.md))
- [ x] Set yourself as the Assignee
- [x ] Tag anyone you would like to review, or @forms-design or @forms-devs
- [ x] Fill in the template below

---

# What

Added summary of file upload and optional questions user research

# How to review

Please check for accuracy.

# Who can review

@Leoarchutowski

### CODE REVIEW

**Review by DavidBiddle — APPROVED** [review]
@oliverquinlan Approving since I think this is a fair summary of the research that was played back 🎉

**Comment by oliverquinlan** [comment]
Thanks David!

**Comment by DavidBiddle** [comment]
@oliverquinlan Are you happy to merge this one?

**Comment by oliverquinlan** [comment]
@DavidBiddle Thanks yes will do!

**Pull request merged**
