### PR TITLE
Documentation outlining content iterations to 'detailed guidance' feature version-1

### PR DESCRIPTION
**Pull request by C-Harry**
# What

This is a new file documenting the content changes made to GOV.UK Forms 'detailed guidance' feature following usability testing. 

Trello card: https://trello.com/c/ITlZU9qd/1047-document-content-updates-to-detailed-guidance-feature-post-testing 

# How to review

1. Check that the content makes sense - is it a clear representation of the changes made and the rationale behind these changes?
1. Is the Markdown correct? 
2. Is this level of detail appropriate/helpful?

### CODE REVIEW

**Review by christophercameron-ixd — COMMENTED** [review]
I think this looks good to go.

**Review by christophercameron-ixd — APPROVED** [review]

**Review by C-Harry — COMMENTED** [review]
All good!

**Review by C-Harry — COMMENTED** [review]
Think this is ready now

**Review by christophercameron-ixd — APPROVED** [review]
Happy to go

**Review by DavidBiddle — APPROVED** [review]

**Pull request merged**
