### PR TITLE
2024 03 13 prototype version 5 updates

### PR DESCRIPTION
**Pull request by christophercameron-ixd**
# PR Checklist

- [X] Set yourself as the Assignee
- [X] Tag anyone you would like to review, or @forms-design or @forms-devs
- [X] Fill in the template below

---

# What

This update relates to trello card https://trello.com/c/ufNJOUWZ/1427-documentation-fixes-update-prototype-version-5 

- removed unnecessary formatting and content
- added brief write up of changes
- fixed screenshot descriptions that were missed

# How to review

1. Semantic: Do you agree with the changes?
2. Syntactic: Spelling, grammar, etc.
3. Is there anything that’s been missed? 
4. Do we need to provide more detail about the changes or is this enough? 

# Who can review

Anyone in the team, but it would be really useful if @hannahkc can take a look.

### CODE REVIEW

**Comment by oliverquinlan** [comment]
Looks good!

**Review by oliverquinlan — APPROVED** [review]
Looks good!

**Review by C-Harry — APPROVED** [review]
Suggested a few changes to wording to help readability/comprehension.

**Comment by hannahkc** [comment]
I might be missing something but in this one it says we reinstated the ‘number’ answer type, but the screenshot doesn't show it?

**Comment by christophercameron-ixd** [comment]
> I might be missing something but in this one it says we reinstated the ‘number’ answer type, but the screenshot doesn't show it?

Yeah, I could update it. It was just that we didn’t actually have it showing other than when the team did their CSL talks, where they used the feature flag to show it :/ 
What do you think makes most sense?

**Review by hannahkc — APPROVED** [review]
Banging!

**Pull request merged**
