### PR TITLE
Add ADR for using GOV.UK Organisation API

### PR DESCRIPTION
**Pull request by lfdebrux**
# What

Document the decision to use the GOV.UK organisation API. See [ADR018](./ADR/ADR018-use-govuk-organisation-api.md) and ticket https://trello.com/c/kKEiA0Bq for details.

# How to review

1. Semantic: Do you agree with the changes?
1. Syntactic: Spelling, grammar, etc.

# Who can review

- Product manager
- Tech architect
- Developers
- Content designer
- Tech writer

### CODE REVIEW

**Review by DavidBiddle — DISMISSED** [review]
Looks good to me - clear and comprehensive run down of the reasons for the decision, and matches the discussions we've had on this previously.

**Review by cadmiumcat — APPROVED** [review]
👍 this makes sense

**Comment by danworth** [comment]
I can see the benefit of this in that we keep the organisations to some official list. I can see that also presenting a limitation in  how services might be able to use Forms which may or may not be a problem. On Pay for example, we had multiple accounts from the same government service/council to represent how they saw things internally. I believe our authorisation is based upon Org (and the users role). So if multiple teams within say HMRC (for which there is one org listed but is a very large organisation) wanted to maintain separate forms/permissions based upon the internal structure of HMRC can that be done e.g. "HMRC team 1" and "HMRC team 2" or do we not see that as a user need?

**Comment by lfdebrux** [comment]
> I can see the benefit of this in that we keep the organisations to some official list. I can see that also presenting a limitation in how services might be able to use Forms which may or may not be a problem. On Pay for example, we had multiple accounts from the same government service/council to represent how they saw things internally. I believe our authorisation is based upon Org (and the users role). So if multiple teams within say HMRC (for which there is one org listed but is a very large organisation) wanted to maintain separate forms/permissions based upon the internal structure of HMRC can that be done e.g. "HMRC team 1" and "HMRC team 2" or do we not see that as a user need?

Great point. We've discussed this with product peeps, we're currently thinking that having teams that are at sub-organisation level will be further down the line, maybe after public beta. It would definitely need a lot more work.

My main thinking from a technical point of view are that the approach in this ADR doesn't necessarily stop us from having organisations that aren't in the GOV.UK list in the database, or even in the same table; as long as we're making sure to keep the content ID reserved for organisations that are known to GOV.UK, and have some method for avoiding clashes with slugs. There will obviously be a great deal many other considerations for our models about how users are assigned to teams, how the hierarchy is expressed, etc., but as we don't support those things currently anyway I feel like it's fine to leave those considerations for later.

**Comment by hannahkc** [comment]
Looks very clear and great to me. The only bit I have a comment in is this: 

> When users come to us asking for their organisation name to be changed, we will have to liaise with publishers who have access to Whitehall Admin. 

I think for government organisations, we ought to be asking them to go through their GOV⁠.⁠UK publishing team and GOV.UK content team to do this as normal - without our involvement. And then we would respond to the change in the relevant way once it's been made in the API? I think this is good as it means the API remains the source of truth and we don't interfere with the process for maintaining and updating it.

**Comment by adamrobertson-gds** [comment]
Looks good to me, thanks!

**Comment by lfdebrux** [comment]
> Looks very clear and great to me. The only bit I have a comment in is this:
> 
> > When users come to us asking for their organisation name to be changed, we will have to liaise with publishers who have access to Whitehall Admin.
> 
> I think for government organisations, we ought to be asking them to go through their GOV⁠.⁠UK publishing team and GOV.UK content team to do this as normal - without our involvement. And then we would respond to the change in the relevant way once it's been made in the API? I think this is good as it means the API remains the source of truth and we don't interfere with the process for maintaining and updating it.

Makes sense @hannahkc. If I update that line to read

> When users come to us asking for their organisation name to be changed, we will have to tell them to talk to publishers in their organisation who have access to Whitehall Admin or to the GOV.UK content team.

does that better express what you'd expect?

**Review by hannahkc — APPROVED** [review]

**Pull request merged**
