### PR TITLE
ADR for adding another answer

### PR DESCRIPTION
**Pull request by SamJamCul**
# PR Checklist

- [x] If you are proposing a new decision record document, used the right template for that
      - ([ADR](https://github.com/alphagov/forms/blob/main/ADR/ADRXXX-architecture-decision-record-template.md), [decision-record](https://github.com/alphagov/forms/blob/main/decision-record/DRXXX-decision-record-template.md), engagement, [research](https://github.com/alphagov/forms/blob/main/research/YYYY-MM-DD-template.md))
- [x] Set yourself as the Assignee
- [x] Tag anyone you would like to review, or @forms-design or @forms-devs
- [ ] Fill in the template below

---

* [Rendered view](https://github.com/alphagov/forms/blob/adr-reaplacing-form-ids-in-urls/ADR/ADR034-add-another-answer-data-model.md)
* [Related spike](https://github.com/alphagov/forms-api/pull/509)

# What
https://trello.com/c/pCD4fbNi/1583-spike-work-out-how-to-account-for-routing-and-question-sets

This ADR is being closed in favour of recreating it as an RFC

https://github.com/alphagov/forms/discussions/174

Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.

### CODE REVIEW

**Comment by chao-xian** [comment]
According to the ERD: 
* `Step` and `QuestionSet` is 1-n
*  while _also_ 1-1 through `Step` - `Positionable` - `QuestionSet`

* Have I understood that right?

**Comment by chao-xian** [comment]
Does `Positionable` have any attributes to hold state?

**Comment by chao-xian** [comment]
Thanks @stephencdaly for pointing me to the related spike which answers my question about what attribute Positionable would have

**Comment by stephencdaly** [comment]
> Thanks @stephencdaly for pointing me to the related spike which answers my question about what attribute Positionable would have

Possibly our attempt at an entity relationship diagram isn't the best. We were trying to show that a "positionable" is either a Question or QuestionSet, but maybe there's a better way to represent that.

**Comment by stephencdaly** [comment]
> According to the ERM diagram:
> 
> * `Step` and `QuestionSet` is 1-n
> * while _also_ 1-1 through `Step` - `Positionable` - `QuestionSet`
> 
> Have I understood that right?

QuestionSet -> Step is 1-n, i.e. a question set can have multiple steps. This association is through the `parent_question_set_id` on a step

**Comment by chao-xian** [comment]
@stephencdaly thanks for clarifying

**Pull request closed without merging**
