### PR TITLE
Add ADR035: offer Amazon S3 for form submissions

### PR DESCRIPTION
**Pull request by james-sheppard-gov-uk**
[Rendered view](https://github.com/alphagov/forms/blob/adr-use-amazon-s3-for-submissions/ADR/ADR035-offer-amazon-s3-form-submissions.md)

# PR Checklist

- [x] If you are proposing a new decision record document, used the right template for that
      - ([ADR](https://github.com/alphagov/forms/blob/main/ADR/ADRXXX-architecture-decision-record-template.md), [decision-record](https://github.com/alphagov/forms/blob/main/decision-record/DRXXX-decision-record-template.md), engagement, [research](https://github.com/alphagov/forms/blob/main/research/YYYY-MM-DD-template.md))
- [x] Set yourself as the Assignee
- [x] Tag anyone you would like to review, or @forms-design or @forms-devs
- [x] Fill in the template below

---

# What

A new ADR to allow form submissions to be sent to Amazon S3.

# How to review

1. Semantic: Do you agree with the changes?
2. Syntactic: Spelling, grammar, etc.

# Who can review

Anyone, but in particular those who worked on the Amazon S3 spike.

### CODE REVIEW

**Review by chao-xian — APPROVED** [review]
Ah thank you James!

**Comment by lfdebrux** [comment]
I worry about what happens if the team managing the S3 bucket accidentally changes the bucket access or configuration in a way that stops us being able to upload documents to it... what will happen to form submissions if the S3 upload doesn't work?

**Comment by DavidBiddle** [comment]
@lfdebrux there's a section on this in the [spike doc](https://docs.google.com/document/d/1Td8oW_hzfyi2WG_21vh0ZU8jJAg4Nw5cshfXnFDfJW0/edit?tab=t.0#heading=h.hcgwf4zfrca7):

> To start with we can replicate the current behaviour with email submissions via Notify, where an error message is shown to the form submitter and they are obliged to resubmit.
>  
>  User research has also suggested that some users would like to receive an email notification that submission failed. This would be basic to start with and the call to action would just be to contact the GOV.UK Forms team. This implies we might want to allow configuration of a support email, to which submission failure notifications would be sent.
>
> In future we could look at temporarily storing submissions so that they can be processed asynchronously. This would provide robustness against submission failures for all submission types (e.g. Notify and SES).
>
> This would allow retries for failed submissions, and would retain failed submission data for a time to allow inspection and replaying submission. This would also allow form fillers to continue submitting forms, even if the submission pipeline isn’t working.

@james-sheppard-gov-uk do you think it's worth incorporating any of that information in here?

**Comment by james-sheppard-gov-uk** [comment]
Thanks for your comments @lfdebrux and @DavidBiddle - I've made a few additions, please could you take another look?

**Review by DavidBiddle — APPROVED** [review]
Looks good to me 🎉

**Review by lfdebrux — APPROVED** [review]

**Pull request merged**
